---
- name: Deploy Server On Node1
  hosts: server
  become: yes
  gather_facts: no
  vars:
          git_repo_url: https://github.com/SyedMustafaImam/Ansible-SclaPlex-Deployment
          repo_path: /home/ubuntunode1/nodejsfileserver
          repo_branch: main
  tasks:
          - name: Run the equivalent of "apt get-update"
            apt:
                    update_cache: yes
          - name: Ansible shell module multiple commands
            shell: 'curl -fsSL https://deb.nodesource.com/stepup_14.x | sudo -E bash -'
          - name: Install required Packages
            apt: name={{ item }} state=present
            with_items:
                    - git
                    - curl
                    - nodejs
                    - npm
          - name: Clone a public repository
            git:
                    repo: "https://github.com/SyedMustafaImam/Ansible-SclaPlex-Deployment"
                    dest: "/home/ubuntunode1/nodejsfileserver"
                    version: "main"
                    accept_hostkey: yes
                    force: yes
          - name: Install nodemon globally
            community.general.npm:
                    name: nodemon
                    state: latest
                    global: yes
          - name: Install packages based on package.json using the npm
            community.general.npm:
                    path: "/home/ubuntunode1/nodejsfileserver/server/"
                    state: latest
          - name: start the application
            command: nodemon &
            args:
                    chdir: "/home/ubuntunode1/nodejsfileserver/server/"