---
- name: Deploy Client On Node2
  hosts: client
  become: yes
  gather_facts: no
  vars:
          git_repo_url: https://github.com/SyedMustafaImam/Ansible-SclaPlex-Deployment
          repo_path: /home/ubuntunode2/nodejsfileclient
          repo_branch: main
  tasks:
          - name: Run the equivalent of "apt get-update"
            apt:
                    update_cache: yes
          - name: Ansible shell module multiple commands
            shell: 'curl -fsSL https://deb.nodesource.com/stepup_14.x | sudo -E bash -'
          - name: Install required Packages
            apt: name={{ item }} state=present
            with_items:
                    - git
                    - curl
                    - nodejs
                    - npm
          - name: Clone a public repository
            git:
                    repo: "https://github.com/SyedMustafaImam/Ansible-SclaPlex-Deployment"
                    dest: "/home/ubuntunode2/nodejsfileclient"
                    version: "main"
                    accept_hostkey: yes
                    force: yes
          - name: Install yarn globally
            community.general.npm:
                    name: yarn
                    state: latest
                    global: yes
          - name: Install packages based on package.json using the yarn
            community.general.yarn:
                    path: "/home/ubuntunode2/nodejsfileclient/client/"
                    state: latest
          - name: start the application
            command: yarn start
            args:
                    chdir: "/home/ubuntunode2/nodejsfileclient/client/"